### ISSUE TITLE
Missing function 'extract_from_idx'

### ISSUE THREAD

**Issue by ijcruic** [youweiliang/ConsistentGraphLearning#1]
Both DGF and SGF functions are missing a helper function called 'extract_from_idx' which is on lines 45 and 55 in SGF and 45 in DGF. The example provided in the README does not work without this function. 
```matlab
>> [nmi, label] = SGF(X, Y, knn, beta, gamma);
Undefined function or variable 'extract_from_idx'.

Error in SGF (line 45)
        [~, tp] = extract_from_idx(ONE, idx{i});
```

**Comment by youweiliang** [comment]
@ijcruic Sorry! I have just added some lost files. It should work correctly now. Be sure to add some helper files by `addpath('MinMaxSelection')` in MATLAB command window.
