### ISSUE TITLE
Can this code be executed directly?

### ISSUE THREAD

**Issue by dugzzuli** [youweiliang/ConsistentGraphLearning#2]
After I downloaded this code, I tested it according to the readme.md file, but I always reported an error:: "The matrix dimensions must be consistent".

**Comment by dugzzuli** [comment]
您好。我用的是2016amatlab运行这个代码但是总是无法运行。
knn.m总会出现错误:

> 错误使用  .* 
> 矩阵维度必须一致。
> 
> 出错 distance_kNN (line 11)
> rowidx = ones(knn, n) .* [1:n];

因为.* 这个运算符在我的版本matlab中总是出现问题（extract_from_idx.m中也出现问题），我想请问一下您用的是什么版本的matlab?

非感感谢。

**Comment by dugzzuli** [comment]
我按照您的期刊的代码调整，但是之后还是出现错误？

**Comment by youweiliang** [comment]
@dugzzuli 你好，我用的Matlab版本是R2017a。另外，ICDM版本的代码是不能跟期刊版本的混在一起用的。因为我的代码经过在Windows上测试没问题才放到GitHub上的，建议你在出错的那行代码设置一个断点进行debug。

**Comment by dugzzuli** [comment]
好的 好的 谢谢 师兄  有点奇特  我装一下R2017a 试试

**Comment by youweiliang** [comment]
@dugzzuli 如果你把GitHub的其它一些仓库（比如Multi-view_Clustering这个仓库）的文件加入到matlab的搜索路径（path）里，可能里面有些同名的函数文件影响

**Comment by dugzzuli** [comment]
非常感谢 师兄

**Comment by dugzzuli** [comment]
非常感谢师兄
是matlab版本的问题
knn.m中 第11行"rowidx = ones(knn, n) .* [1:n];"，".*"左右两边矩阵在2017中是可以计算的 但是2016中无法计算

**Comment by youweiliang** [comment]
好的，grad to know that : )
